-- Script Completo - Tienda de Pinturas
-- Oracle Database | Puerto: 1522 | Host: localhost | Usuario: admin
-- EJECUTAR CON F5 (Run Script), NO Ctrl+Enter

SET SERVEROUTPUT ON;

-- =====================================
-- LIMPIEZA (orden inverso de dependencias)
-- =====================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('DETALLECOMPRA','DETALLEVENTA','COMPRA','VENTA','PRODUCTO','PROVEEDOR','CLIENTE','COLOR','MARCA','CATEGORIA')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
        DBMS_OUTPUT.PUT_LINE('Tabla ' || t.table_name || ' eliminada.');
    END LOOP;
END;
/

-- =====================================
-- CREACION DE TABLAS
-- =====================================
CREATE TABLE Categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255)
);

CREATE TABLE Marca (
    id_marca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255)
);

CREATE TABLE Color (
    id_color NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_hex VARCHAR2(7)
);

CREATE TABLE Proveedor (
    id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    contacto VARCHAR2(100),
    telefono VARCHAR2(20),
    direccion VARCHAR2(255)
);

CREATE TABLE Cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(20),
    email VARCHAR2(100)
);

CREATE TABLE Producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER(10) DEFAULT 0,
    id_categoria NUMBER NOT NULL,
    id_marca NUMBER NOT NULL,
    id_color NUMBER NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria),
    CONSTRAINT fk_producto_marca FOREIGN KEY (id_marca) REFERENCES Marca(id_marca),
    CONSTRAINT fk_producto_color FOREIGN KEY (id_color) REFERENCES Color(id_color)
);

CREATE TABLE Compra (
    id_compra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(12,2) DEFAULT 0,
    id_proveedor NUMBER NOT NULL,
    CONSTRAINT fk_compra_proveedor FOREIGN KEY (id_proveedor) REFERENCES Proveedor(id_proveedor)
);

CREATE TABLE Venta (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(12,2) DEFAULT 0,
    id_cliente NUMBER NOT NULL,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente)
);

CREATE TABLE DetalleCompra (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER(10) NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detallecompra_compra FOREIGN KEY (id_compra) REFERENCES Compra(id_compra),
    CONSTRAINT fk_detallecompra_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

CREATE TABLE DetalleVenta (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER(10) NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detalleventa_venta FOREIGN KEY (id_venta) REFERENCES Venta(id_venta),
    CONSTRAINT fk_detalleventa_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

-- =====================================
-- VERIFICACION DE TABLAS
-- =====================================
SELECT table_name FROM user_tables ORDER BY table_name;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables;
    DBMS_OUTPUT.PUT_LINE('Tablas creadas correctamente: ' || v_count);
END;
/

-- =====================================
-- DATOS DE PRUEBA
-- =====================================

-- 1. CATEGORIA
INSERT INTO Categoria (nombre, descripcion) VALUES ('Interior', 'Pinturas para espacios interiores');
INSERT INTO Categoria (nombre, descripcion) VALUES ('Exterior', 'Pinturas para fachadas y exteriores');
INSERT INTO Categoria (nombre, descripcion) VALUES ('Barniz', 'Barnices y lacas protectores');
INSERT INTO Categoria (nombre, descripcion) VALUES ('Esmalte', 'Esmaltes sintéticos y acrílicos');
INSERT INTO Categoria (nombre, descripcion) VALUES ('Imprimante', 'Primers y selladores');
INSERT INTO Categoria (nombre, descripcion) VALUES ('Efectos', 'Pinturas con efectos decorativos');

-- 2. MARCA
INSERT INTO Marca (nombre, descripcion) VALUES ('Sherwin-Williams', 'Marca premium estadounidense');
INSERT INTO Marca (nombre, descripcion) VALUES ('Comex', 'Marca líder en México');
INSERT INTO Marca (nombre, descripcion) VALUES ('Berel', 'Pinturas arquitectónicas brasileñas');
INSERT INTO Marca (nombre, descripcion) VALUES ('Vencedor', 'Pinturas económicas ecuatorianas');
INSERT INTO Marca (nombre, descripcion) VALUES ('Pintuco', 'Marca colombiana de alta calidad');

-- 3. COLOR
INSERT INTO Color (nombre, codigo_hex) VALUES ('Blanco', '#FFFFFF');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Blanco Hueso', '#F5F5DC');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Beige', '#F5F5DC');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Gris Claro', '#D3D3D3');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Gris Oscuro', '#A9A9A9');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Negro', '#000000');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Rojo', '#FF0000');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Rojo Ladrillo', '#B22222');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Azul Marino', '#000080');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Azul Cielo', '#87CEEB');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Verde Oliva', '#556B2F');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Verde Menta', '#98FF98');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Amarillo', '#FFFF00');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Naranja', '#FFA500');
INSERT INTO Color (nombre, codigo_hex) VALUES ('Marrón', '#8B4513');

-- 4. PROVEEDOR
INSERT INTO Proveedor (nombre, contacto, telefono, direccion) VALUES ('Distribuidora Nacional de Pintura', 'Carlos Mendez', '555-0101', 'Av. Industrial 500, Ciudad');
INSERT INTO Proveedor (nombre, contacto, telefono, direccion) VALUES ('Químicos del Sur S.A.', 'Ana Lucía Rivas', '555-0102', 'Calle Química 123, Sur');
INSERT INTO Proveedor (nombre, contacto, telefono, direccion) VALUES ('Importadora Color Global', 'Pedro Jiménez', '555-0103', 'Zona Franca Km 15, Norte');
INSERT INTO Proveedor (nombre, contacto, telefono, direccion) VALUES ('Pinturas y Solventes ABC', 'Laura Gómez', '555-0104', 'Boulevard Comercial 789, Este');
INSERT INTO Proveedor (nombre, contacto, telefono, direccion) VALUES ('Proveedora de Acabados', 'Roberto Díaz', '555-0105', 'Periférico Sur 456, Oeste');

-- 5. CLIENTE
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Constructora Omega S.A.', 'Av. Principal 1000, Ciudad', '555-1001', 'compras@omega.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Ferremundo Cía. Ltda.', 'Calle del Comercio 200, Centro', '555-1002', 'pedidos@ferremundo.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('María Fernanda López', 'Residencial Los Pinos 5, Casa 12', '555-1003', 'maria.lopez@gmail.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Taller de Arte y Color', 'Barrio San José 3-45', '555-1004', 'info@tallerarteycolor.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Inmobiliaria del Valle', 'Av. Siempre Viva 742, Valle Alto', '555-1005', 'admin@inmobiliariadelvalle.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Carlos Ruiz', 'Urb. Las Flores, Calle 3, Casa 8', '555-1006', 'cruiz@hotmail.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Mueblería El Artesano', 'Zona Industrial 12, Bodega 4', '555-1007', 'ventas@muebleriaelartesano.com');
INSERT INTO Cliente (nombre, direccion, telefono, email) VALUES ('Gobierno Provincial', 'Palacio Provincial, Plaza Mayor 1', '555-1008', 'contrataciones@gobprov.gov');

-- 6. PRODUCTO
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Interior Blanca Premium 4L', 'Pintura lavable mate para interiores', 25.50, 120, 1, 1, 1);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Interior Beige Mate 4L', 'Pintura interior color beige mate', 24.00, 80, 1, 2, 3);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Exterior Blanco Hueso 4L', 'Pintura acrílica para exteriores', 32.00, 60, 2, 1, 2);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Exterior Rojo Ladrillo 4L', 'Pintura acrílica antimoho', 35.00, 45, 2, 3, 8);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Barniz Transparente Mate 1L', 'Barniz poliuretano para madera', 18.00, 200, 3, 2, 1);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Barniz Marino Brillante 1L', 'Barniz marino para exteriores', 22.50, 150, 3, 5, 1);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Esmalte Sintético Negro 1L', 'Esmalte sintético brillante', 15.00, 90, 4, 4, 6);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Esmalte Acrílico Blanco 1L', 'Esmalte acrílico satinado', 16.50, 110, 4, 1, 1);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Imprimante Multipropósito 4L', 'Primer sellador para paredes', 20.00, 75, 5, 2, 1);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Imprimante Anticorrosivo 1L', 'Primer para superficies metálicas', 19.00, 65, 5, 1, 4);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Efecto Texturizado 4L', 'Pintura decorativa texturizada', 40.00, 30, 6, 3, 3);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Interior Azul Cielo 4L', 'Pintura interior lavable satinada', 26.00, 55, 1, 5, 10);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Exterior Verde Oliva 4L', 'Pintura exterior resistente UV', 34.00, 40, 2, 2, 11);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Esmalte Sintético Rojo 1L', 'Esmalte sintético alto brillo', 15.00, 85, 4, 4, 7);
INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color) VALUES ('Pintura Efecto Yeso Veneciano 4L', 'Acabado decorativo veneciano', 55.00, 20, 6, 1, 3);

-- 7. COMPRA (totales calculados de DetalleCompra)
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 30, 980.00, 1);
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 25, 772.50, 2);
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 20, 1470.00, 3);
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 15, 522.50, 1);
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 10, 995.00, 4);
INSERT INTO Compra (fecha, total, id_proveedor) VALUES (SYSDATE - 5, 941.50, 5);

-- 8. VENTA (totales calculados de DetalleVenta)
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 28, 270.00, 1);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 22, 134.00, 3);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 18, 402.00, 2);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 14, 94.00, 6);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 8, 425.00, 5);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 3, 233.00, 4);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE - 1, 591.00, 7);
INSERT INTO Venta (fecha, total, id_cliente) VALUES (SYSDATE, 1520.00, 8);

-- 9. DETALLE COMPRA
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (1, 1, 30, 18.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (1, 8, 20, 11.50);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (1, 9, 15, 14.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (2, 2, 25, 16.50);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (2, 5, 30, 12.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (3, 3, 20, 24.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (3, 4, 15, 26.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (3, 13, 25, 24.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (4, 6, 20, 16.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (4, 10, 15, 13.50);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (5, 7, 40, 10.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (5, 14, 30, 10.50);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (5, 11, 10, 28.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (6, 1, 20, 18.00);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (6, 12, 15, 18.50);
INSERT INTO DetalleCompra (id_compra, id_producto, cantidad, precio_unitario) VALUES (6, 15, 8, 38.00);

-- 10. DETALLE VENTA
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (1, 1, 5, 25.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (1, 9, 3, 20.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (1, 8, 5, 16.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (2, 2, 3, 24.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (2, 5, 2, 18.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (2, 12, 1, 26.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (3, 3, 5, 32.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (3, 4, 4, 35.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (3, 13, 3, 34.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (4, 7, 2, 15.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (4, 14, 3, 15.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (4, 10, 1, 19.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (5, 1, 10, 25.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (5, 6, 4, 22.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (5, 11, 2, 40.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (6, 5, 5, 18.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (6, 15, 2, 55.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (6, 8, 2, 16.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (7, 4, 6, 35.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (7, 3, 4, 32.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (7, 9, 5, 20.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (7, 1, 6, 25.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (8, 1, 20, 25.50);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (8, 3, 15, 32.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (8, 12, 10, 26.00);
INSERT INTO DetalleVenta (id_venta, id_producto, cantidad, precio_unitario) VALUES (8, 5, 15, 18.00);

-- =====================================
-- VERIFICACION
-- =====================================
SELECT 'Categoria' AS tabla, COUNT(*) AS registros FROM Categoria
UNION ALL SELECT 'Marca', COUNT(*) FROM Marca
UNION ALL SELECT 'Color', COUNT(*) FROM Color
UNION ALL SELECT 'Proveedor', COUNT(*) FROM Proveedor
UNION ALL SELECT 'Cliente', COUNT(*) FROM Cliente
UNION ALL SELECT 'Producto', COUNT(*) FROM Producto
UNION ALL SELECT 'Compra', COUNT(*) FROM Compra
UNION ALL SELECT 'Venta', COUNT(*) FROM Venta
UNION ALL SELECT 'DetalleCompra', COUNT(*) FROM DetalleCompra
UNION ALL SELECT 'DetalleVenta', COUNT(*) FROM DetalleVenta;

COMMIT;
/

-- =====================================
-- CONSULTAS DE EJEMPLO
-- =====================================

-- Ver todos los productos
SELECT * FROM Producto;

-- Productos con su categoria y marca
SELECT p.nombre AS producto, c.nombre AS categoria, m.nombre AS marca, p.precio, p.stock
FROM Producto p
JOIN Categoria c ON p.id_categoria = c.id_categoria
JOIN Marca m ON p.id_marca = m.id_marca;

-- Ventas realizadas con cliente
SELECT v.id_venta, c.nombre AS cliente, v.fecha, v.total
FROM Venta v
JOIN Cliente c ON v.id_cliente = c.id_cliente;

-- Productos con stock bajo (< 50)
SELECT nombre, stock FROM Producto WHERE stock < 50;

-- Total de ventas
SELECT SUM(total) AS total_ventas FROM Venta;

-- =====================================
-- EJEMPLOS INSERT
-- =====================================
INSERT INTO Categoria (nombre, descripcion) VALUES ('Industrial', 'Pinturas para industria');

INSERT INTO Cliente (nombre, direccion, telefono, email)
VALUES ('Juan Perez', 'Calle 10', '555-9999', 'juan@gmail.com');

INSERT INTO Producto (nombre, descripcion, precio, stock, id_categoria, id_marca, id_color)
VALUES ('Pintura Azul Mate 4L', 'Pintura azul para interiores', 28.50, 40, 1, 2, 9);

COMMIT;

-- =====================================
-- EJEMPLOS UPDATE
-- =====================================
UPDATE Producto SET precio = 30.00 WHERE id_producto = 1;
UPDATE Producto SET stock = stock + 20 WHERE id_producto = 3;
UPDATE Cliente SET telefono = '555-8888' WHERE id_cliente = 2;

COMMIT;

-- =====================================
-- EJEMPLOS DELETE (orden correcto: hijos antes que padres)
-- =====================================

-- Eliminar ventas con total < 100
DELETE FROM DetalleVenta WHERE id_venta IN (SELECT id_venta FROM Venta WHERE total < 100);
DELETE FROM Venta WHERE total < 100;

-- Eliminar producto 15 (primero sus detalles)
DELETE FROM DetalleVenta WHERE id_producto = 15;
DELETE FROM DetalleCompra WHERE id_producto = 15;
DELETE FROM Producto WHERE id_producto = 15;

-- Eliminar cliente 8 (primero sus ventas y detalles)
DELETE FROM DetalleVenta WHERE id_venta IN (SELECT id_venta FROM Venta WHERE id_cliente = 8);
DELETE FROM Venta WHERE id_cliente = 8;
DELETE FROM Cliente WHERE id_cliente = 8;

COMMIT;
/