GRANT CREATE SESSION TO PROYECTO_KARDEX;

GRANT CREATE TABLE TO PROYECTO_KARDEX;
ALTER USER PROYECTO_KARDEX QUOTA UNLIMITED ON DATA;

-- Permiso para crear Vistas
GRANT CREATE VIEW TO PROYECTO_KARDEX;

-- Permiso para crear Triggers (Disparadores)
GRANT CREATE TRIGGER TO PROYECTO_KARDEX;

GRANT CREATE SEQUENCE TO PROYECTO_KARDEX;

GRANT CREATE ANY INDEX TO PROYECTO_KARDEX;

COMMIT;