-- Proyecto Pinturas
CREATE USER proyecto_pinturas IDENTIFIED BY "123456789Op{";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO proyecto_pinturas;

-- Proyecto Kardex
CREATE USER proyecto_kardex IDENTIFIED BY "123456789Op{";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO proyecto_hotel;

-- Ptoyecto Nomina
CREATE USER proyecto_nomina IDENTIFIED BY "123456789Op{";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO Proyecto_nomina;

-- Proyecto Final
CREATE USER proyecto_final IDENTIFIED BY "123456789Op{";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO proyecto_final;